
const DEFAULT_KONG_NAME = "NoKongName";

const DEFAULT_GUILD_ID = "NoId";
const DEFAULT_GUILD_TYPE = "NoType";
const DEFAULT_GUILD_NAME = "NoName";

const DEFAULT_GUILD_COMBINED_ID = DEFAULT_GUILD_ID + "|" + DEFAULT_GUILD_TYPE + "|" + DEFAULT_GUILD_NAME;
